import { useState } from "react";
import { Check, CreditCard, Lock, Plus, ShieldCheck, Snowflake } from "lucide-react";
import { toast } from "sonner";
import { AppShell, ScreenHeader } from "@/components/AppShell";

/** Precision Ledger design: payment cards are controlled instruments with status visible at a glance. */

export default function Cards() {
  const [frozen, setFrozen] = useState(false); const [adding, setAdding] = useState(false); const [added, setAdded] = useState(false);
  const toggleFrozen = () => { setFrozen((value) => !value); toast(frozen ? "Card unfrozen" : "Card frozen", { description: frozen ? "New payments can now be made." : "New card payments have been paused." }); };
  const addCard = (event: React.FormEvent) => { event.preventDefault(); setAdded(true); setAdding(false); toast("Virtual card created", { description: "A new FinFlex virtual card is ready." }); };
  return <AppShell><ScreenHeader eyebrow="Payment controls" title="Cards, made" accent="clear." detail="Manage active payment methods and create a private virtual card."><button className="screen-action" type="button" onClick={() => setAdding((open) => !open)}><Plus size={14} /> Add card</button></ScreenHeader>{adding && <form className="add-card-form" onSubmit={addCard}><div><p className="drawer-eyebrow">New virtual card</p><strong>Create a purpose-specific payment method.</strong></div><label className="field-label">Card name<input defaultValue="Project purchases" /></label><button className="screen-primary-action" type="submit">Create card <Check size={14} /></button></form>}<section className="cards-layout"><article className={`physical-card ${frozen ? "is-frozen" : ""}`}><div><span>FinFlex</span><ShieldCheck size={19} /></div><div className="card-metal-chip" /><p className="mono">•••• •••• •••• 8967</p><footer><span>Mira Johnson</span><strong>VISA</strong></footer>{frozen && <div className="card-freeze-layer"><Snowflake size={20} /> Frozen</div>}</article><article className="screen-panel card-control-panel"><div className="screen-panel-head"><div><p>FinFlex Visa</p><span>Primary spending card · ending 8967</span></div><span className={`card-status ${frozen ? "is-frozen" : ""}`}>{frozen ? "Frozen" : "Active"}</span></div><div className="card-control-stat"><span>Available to spend</span><strong className="mono">$4,568.00</strong></div><div className="card-controls"><button type="button" onClick={toggleFrozen}><Snowflake size={16} /><span>{frozen ? "Unfreeze card" : "Freeze card"}</span></button><button type="button" onClick={() => toast("Card details", { description: "Your card number and security details are protected." })}><CreditCard size={16} /><span>View details</span></button><button type="button" onClick={() => toast("Security controls", { description: "Merchant locks and payment alerts are ready to configure." })}><Lock size={16} /><span>Security controls</span></button></div></article>{added && <article className="virtual-card"><p>Virtual · Project purchases</p><strong className="mono">•••• 4031</strong><span><Check size={13} /> Ready to use</span></article>}</section></AppShell>;
}
