import { useMemo, useState } from "react";
import { Download, Filter, Search } from "lucide-react";
import { toast } from "sonner";
import { AppShell, ScreenHeader } from "@/components/AppShell";
import { TRANSACTIONS, type Transaction, type TransactionKind } from "@/lib/finance-data";
import { TransactionDrawer } from "@/components/TransactionDrawer";

/** Precision Ledger design: the ledger is a calm, searchable system of record rather than a decorative table. */

export default function Payments() {
  const [query, setQuery] = useState(""); const [tab, setTab] = useState<"All" | TransactionKind>("All"); const [showFilters, setShowFilters] = useState(false); const [selected, setSelected] = useState<Transaction | null>(null); const [clearedOnly, setClearedOnly] = useState(false);
  const rows = useMemo(() => TRANSACTIONS.filter((item) => (tab === "All" || item.type === tab) && `${item.name} ${item.category} ${item.counterparty}`.toLowerCase().includes(query.toLowerCase()) && (!clearedOnly || item.type === "Spending")), [query, tab, clearedOnly]);
  return <AppShell><ScreenHeader eyebrow="Complete ledger" title="Every payment," accent="accounted for." detail="Search, inspect, and organize your connected activity."><button className="screen-action" type="button" onClick={() => toast("Ledger exported", { description: "A CSV export has been prepared for this local workspace." })}><Download size={14} /> Export CSV</button></ScreenHeader><section className="screen-panel ledger-panel"><div className="ledger-toolbar"><label className="ledger-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search merchant, category, or counterparty" /></label><button className={`ledger-filter-button ${showFilters ? "is-active" : ""}`} type="button" onClick={() => setShowFilters((open) => !open)}><Filter size={14} /> Filter</button></div>{showFilters && <div className="ledger-filter-row"><span>Quick filter</span><button type="button" className={clearedOnly ? "is-active" : ""} onClick={() => setClearedOnly((active) => !active)}>{clearedOnly ? "Spending only" : "All cleared activity"}</button></div>}<div className="ledger-tabs">{(["All", "Income", "Spending"] as const).map((item) => <button type="button" key={item} className={tab === item ? "is-active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div><div className="ledger-table-head"><span>Merchant</span><span>Category</span><span>Date</span><span>Amount</span></div><div className="full-transaction-list">{rows.map((transaction) => { const Icon = transaction.icon; return <button className="full-transaction" type="button" onClick={() => setSelected(transaction)} key={transaction.id}><span className="transaction-left"><span className="merchant-icon"><Icon size={15} /></span><span className="merchant-details"><strong>{transaction.name}</strong><small>{transaction.counterparty}</small></span></span><span className="table-category">{transaction.category}</span><span className="table-date">{transaction.detail}</span><span className={`amount mono ${transaction.amount.startsWith("+") ? "credit" : ""}`}>{transaction.amount}</span></button>; })}{!rows.length && <p className="empty-ledger">No transaction matches your search.</p>}</div></section><TransactionDrawer transaction={selected} onClose={() => setSelected(null)} /></AppShell>;
}
