import { useState } from "react";
import { ArrowDownToLine, ArrowLeftRight, Check, ChevronDown, Plus, Repeat2, Users } from "lucide-react";
import { toast } from "sonner";
import { AppShell, ScreenHeader } from "@/components/AppShell";

/** Precision Ledger design: money movement is intentional, with a legible source-to-destination path. */

const ACCOUNTS = ["FinFlex Checking •••• 2048", "FinFlex Savings •••• 1264", "FinFlex Visa •••• 8967"];
export default function Transfers() {
  const [source, setSource] = useState(ACCOUNTS[0]); const [destination, setDestination] = useState(ACCOUNTS[1]); const [amount, setAmount] = useState("250.00"); const [memo, setMemo] = useState("August savings"); const [recipientsOpen, setRecipientsOpen] = useState(false); const [submitted, setSubmitted] = useState(false);
  const swapAccounts = () => { setSource(destination); setDestination(source); };
  const submitTransfer = (event: React.FormEvent) => { event.preventDefault(); setSubmitted(true); toast("Transfer scheduled", { description: `$${amount || "0.00"} will move on August 9.` }); };
  return <AppShell><ScreenHeader eyebrow="Money movement" title="Move money" accent="with intent." detail="Schedule an internal transfer or prepare a recipient payment."><button className="screen-action" type="button" onClick={() => setRecipientsOpen((open) => !open)}><Users size={14} /> Manage recipients</button></ScreenHeader>{recipientsOpen && <section className="recipient-strip"><div><Users size={17} /><span><strong>Saved recipients</strong><small>Ari Patel, City Utilities, Northline Studio</small></span></div><button type="button" onClick={() => toast("Recipient flow", { description: "A secure recipient setup flow would open here." })}><Plus size={14} /> Add recipient</button></section>}<section className="transfer-layout"><form className="screen-panel transfer-form" onSubmit={submitTransfer}><div className="screen-panel-head"><div><p>New transfer</p><span>Funds available immediately</span></div><span className="transfer-available mono">$7,842.00</span></div><label className="field-label">From<select value={source} onChange={(event) => setSource(event.target.value)}>{ACCOUNTS.map((account) => <option key={account}>{account}</option>)}</select></label><button type="button" className="swap-button" aria-label="Swap accounts" onClick={swapAccounts}><ArrowLeftRight size={16} /></button><label className="field-label">To<select value={destination} onChange={(event) => setDestination(event.target.value)}>{ACCOUNTS.map((account) => <option key={account}>{account}</option>)}</select></label><div className="field-pair"><label className="field-label">Amount<div className="amount-field"><span>$</span><input value={amount} inputMode="decimal" onChange={(event) => setAmount(event.target.value.replace(/[^0-9.]/g, ""))} /></div></label><label className="field-label">Frequency<select defaultValue="Once"><option>Once</option><option>Weekly</option><option>Monthly</option></select></label></div><label className="field-label">Memo<input value={memo} onChange={(event) => setMemo(event.target.value)} /></label><button className="screen-primary-action full-width" type="submit">Schedule transfer <ArrowDownToLine size={15} /></button></form><aside className="transfer-side"><article className="screen-panel transfer-summary"><p className="drawer-eyebrow">Transfer path</p><div className="transfer-path"><span><i>01</i>{source.split(" •")[0]}</span><b><Repeat2 size={16} /></b><span><i>02</i>{destination.split(" •")[0]}</span></div><p>Transfers between your FinFlex accounts are instant and fee-free.</p></article><article className={`screen-panel confirmation-card ${submitted ? "is-visible" : ""}`}><Check size={19} /><div><strong>{submitted ? "Transfer ready" : "No transfer scheduled"}</strong><span>{submitted ? `Your ${memo || "transfer"} is set for tomorrow.` : "Complete the form to schedule a move."}</span></div></article></aside></section></AppShell>;
}
